- set_fact:
    home_path: "{{ ansible_env.HOME }}"

- name: Update apt cache
  apt: update_cache=yes
  when: update

- name: Install tmux and git
  apt: name={{ item }} state=present
  with_items:
    - tmux
    - git
  when: install
  become: true

- name: Enable history sharing in .bashrc
  lineinfile: dest="{{ home_path }}/.bashrc" state=present line={{ item }}
  with_items:
    - export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
  when: share_history

- name: Enable aliases .bashrc
  lineinfile: dest="{{ home_path }}/.bashrc" state=present line={{ item }}
  with_items:
    - alias tl='tmux ls'
    - alias ta='tmux attach -t'
    - alias tk='tmux kill-session -t'
  when: aliases

- name: Check if tmux v2.0 is installed
  raw: echo `tmux -V | cut -d' ' -f2`'<'2.0 | bc -l
  register: tmux_version

- name: Upgrade to tmux v2.0
  command: "{{ item }}"
  with_items:
    - apt-get update
    - apt-get install -y python-software-properties software-properties-common
    - add-apt-repository -y ppa:pi-rho/dev
    - apt-get update
    - apt-get install -y tmux=2.0-1~ppa1~t
  when: tmux_upgrade and tmux_version.stdout|trim == "1"
  become: yes
